languageCode = 'en-us'
title = 'Lykeion Theme Example'
theme = 'Lykeion'
themesDir = '../..'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
